/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leitura_e_aprendizagem;

import br.com.jmary.home.Home;
import br.com.jmary.home.beans.Assunto;
import br.com.jmary.home.beans.Materia;
import br.com.jmary.home.beans.Subcategoria;
import br.com.jmary.home.jpa.JPAUtil;
import java.awt.Desktop;
import java.io.File;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicSplitPaneUI;

/**
 *
 * @author Ana
 */
public class BarraJEditorPane extends javax.swing.JPanel {

    Home Home; 
    BookInfo BookInfo;
    HtmlPrincipal HtmlPrincipal;
    JPHtmlPrincipal JPHtmlPrincipal; 
            
    /**
     * Creates new form BarraJEditorPane
     * @param Home2
     * @param JPHtmlPrincipal2
     * @param HtmlPrincipal2
     * @param BookInfo2
     */
    public BarraJEditorPane( Home Home2, JPHtmlPrincipal JPHtmlPrincipal2, HtmlPrincipal HtmlPrincipal2, BookInfo BookInfo2 ) {
        initComponents();
        
        Home = Home2; 
        JPHtmlPrincipal = JPHtmlPrincipal2;
        HtmlPrincipal   = HtmlPrincipal2;
        BookInfo        = BookInfo2;
        
        bt_fazer_exe.setVisible(false);
        bt_criar_exe.setVisible(false);
        lbPdf.setVisible(false);
        
        inicio();
    }
        
    private void inicio(){ 
        new Thread() {   @Override public void run() { try {         
            
            if(BookInfo.tipoNoBanco.equals("ASSUNTO")){
                
                verificarAssunto( BookInfo.idNoBanco ); 
            }
        } catch( Exception e ){ } } }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPosTrees = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_fazer_exe = new javax.swing.JLabel();
        bt_criar_exe = new javax.swing.JLabel();
        lbPdf = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        btPosTrees.setText("<<");
        btPosTrees.setToolTipText("Contrair Descontrair JTREE");
        btPosTrees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPosTrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPosTreesActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/FonteDim.png"))); // NOI18N
        jLabel1.setToolTipText("Diminuir Fonte");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/FontePadrao.png"))); // NOI18N
        jLabel2.setToolTipText("Fonte Tamnho Padrão");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/FonteAum.png"))); // NOI18N
        jLabel3.setToolTipText("Aumentar Fonte");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/impressora.png"))); // NOI18N
        jLabel4.setToolTipText("Imprimir");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/16_chrome.png"))); // NOI18N
        jLabel6.setToolTipText("Abrir Página no Brouser");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        bt_fazer_exe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/java.gif"))); // NOI18N
        bt_fazer_exe.setText("Fazer");
        bt_fazer_exe.setToolTipText("Fazer Exercícios");
        bt_fazer_exe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_fazer_exe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_fazer_exeMousePressed(evt);
            }
        });

        bt_criar_exe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/java.gif"))); // NOI18N
        bt_criar_exe.setText("Criar");
        bt_criar_exe.setToolTipText("Criar Exercícios");
        bt_criar_exe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_criar_exe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_criar_exeMousePressed(evt);
            }
        });

        lbPdf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_leitura_e_aprendizagem/pdf_16_16.gif"))); // NOI18N
        lbPdf.setToolTipText("Abrir Página no Brouser");
        lbPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbPdfMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPosTrees)
                .addGap(18, 18, 18)
                .addComponent(bt_fazer_exe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_criar_exe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(lbPdf)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btPosTrees)
                        .addComponent(jLabel1))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPdf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bt_fazer_exe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bt_criar_exe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btPosTrees, bt_criar_exe, bt_fazer_exe, jLabel1, jLabel2, jLabel3, jLabel4, jLabel6, lbPdf});

    }// </editor-fold>//GEN-END:initComponents

    private void btPosTreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPosTreesActionPerformed
        String tx = btPosTrees.getText().trim();
        switch (tx) {
            case "<<":
                splitPane( 0 );
                btPosTrees.setText(">>");
                break;
            case ">>":
                splitPane( 1 );
                btPosTrees.setText("<<");
                break;
        }
    }//GEN-LAST:event_btPosTreesActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        HtmlPrincipal.alterarFonte(false);        
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        HtmlPrincipal.alterarFonte(true); 
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        HtmlPrincipal.alterarTamanhoFonte(120); 
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        ////////////////////////////////////////////////////////////////////////
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            /*
            List<File> lista_Arquivos = new ArrayList();
            
            File f = new File( HtmlPrincipal.htmlPanePrincipal.getPage().toURI() );
            
            lista_Arquivos.add( f );
         
            O3_Imprimir_Aquivos_Html t1 = new O3_Imprimir_Aquivos_Html( lista_Arquivos );
            t1.setName("O3_Imprimir_Aquivos_Html");
            t1.start(); 
            */
            
            O3_Imprimir_JEditorPane_Html t1 = new O3_Imprimir_JEditorPane_Html( HtmlPrincipal.htmlPanePrincipal );
            t1.setName("O3_Imprimir_Aquivos_Html");
            t1.start();  
        } catch( Exception e ){ } } }.start();
        ////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        ////////////////////////////////////////////////////////////////////////
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            File f = new File( HtmlPrincipal.htmlPanePrincipal.getPage().toURI() );
         
            if (Desktop.isDesktopSupported()) {
                //System.out.println( "URL: " + url);
                Desktop.getDesktop().open( f );
            } 
        } catch( Exception e ){ } } }.start();
        ////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_jLabel6MousePressed

    String materia_X = "";
    String subcaegoria_X = "";
    String assunto_X = "";
    private void bt_fazer_exeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_fazer_exeMousePressed
        String assunto_t = materia_X + " > " + subcaegoria_X + " > " + assunto_X.toUpperCase();
        Home.fazer_Exercicios(assunto_t);
    }//GEN-LAST:event_bt_fazer_exeMousePressed

    private void bt_criar_exeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_criar_exeMousePressed
        String assunto_recebido = materia_X + " > " + subcaegoria_X + " > " + assunto_X.toUpperCase();
        Home.criar_exercicios(assunto_recebido);
    }//GEN-LAST:event_bt_criar_exeMousePressed

    private void lbPdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPdfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbPdfMousePressed
    
    private void verificarAssunto( int id_x ){ 
        try {         
            
            List<Assunto> ListAssunto = null;            
            try{
                Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM JM.ASSUNTO WHERE ID = ?", Assunto.class );
                q.setParameter( 1, id_x );           
                ListAssunto = q.getResultList();
            }catch(Exception e ){}
            
            String rbusca = ""; try{ rbusca = ListAssunto.get(0).getAssunto(); }catch( Exception e ){}
            
            if( !rbusca.equals("") ){
            
                 assunto_X = ListAssunto.get(0).getAssunto();
                 verificarSubcategoria( ListAssunto.get(0).getIdSubcategoria() );
            }
            
        } catch ( Exception e ) {}
    }
    
    private void verificarSubcategoria( int id_x ){ 
        try {         
            
            List<Subcategoria> ListSubcategoria = null;                    
            try{
                Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM JM.SUBCATEGORIA WHERE ID = ?", Subcategoria.class );
                q.setParameter( 1, id_x );            
                ListSubcategoria = q.getResultList();
            }catch(Exception e ){}
                    
            String rbuscaS = ""; try{ rbuscaS = ListSubcategoria.get(0).getSubcategoria(); }catch( Exception e ){}
                    
            if( !rbuscaS.equals("") ){
                    
                subcaegoria_X = ListSubcategoria.get(0).getSubcategoria();
                verificarMateria( ListSubcategoria.get(0).getIdMateria());
            }
            
        } catch ( Exception e ) {}
    }
    
    private void verificarMateria( int id_x ){ 
        try {         
            
            List<Materia> ListMateria = null;            
            try{
                Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM JM.MATERIA WHERE ID = ?", Materia.class );
                q.setParameter(1, id_x );            
                ListMateria = q.getResultList();
            }catch(Exception e ){}
            
            String rbusca = ""; try{ rbusca = ListMateria.get(0).getMateria(); }catch( Exception e ){}
            
            if( !rbusca.equals("") ){
                
                materia_X = ListMateria.get(0).getMateria();
                
                bt_fazer_exe.setVisible(true);
                bt_criar_exe.setVisible(true);
            }
            
        } catch ( Exception e ) {}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPosTrees;
    private javax.swing.JLabel bt_criar_exe;
    private javax.swing.JLabel bt_fazer_exe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel lbPdf;
    // End of variables declaration//GEN-END:variables

    private void splitPane( int zeroOuUm ){
        //spPrincipal.setDividerLocation(80);
        try{
            
            BasicSplitPaneUI ui = (BasicSplitPaneUI)JPHtmlPrincipal.jSplitPaneHtmlPrincipal.getUI();
            JButton oneClick = (JButton)ui.getDivider().getComponent( zeroOuUm );
            oneClick.doClick();
        
        } catch( Exception e ){
            JOptionPane.showMessageDialog(null, "BarraJEditorPane - Método: splitPane\n" + e.getMessage().toString());
        }
    }
    
}
