/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leitura_e_aprendizagem;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.Exportando;

/**
 *
 * @author admin
 */
public class Leitura_e_Aprendizagem_Indice extends javax.swing.JPanel {

    Home Home;
    /**
     * Creates new form Exercicios_00_Portugues_Indice
     * @param Home2
     */
    public Leitura_e_Aprendizagem_Indice( Home Home2) {
        Home = Home2;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbAssunto_1 = new javax.swing.JLabel();
        lbAssunto_2 = new javax.swing.JLabel();
        lbAssunto_3 = new javax.swing.JLabel();
        lbAssunto_4 = new javax.swing.JLabel();
        lbAssunto_5 = new javax.swing.JLabel();
        lbAssunto_6 = new javax.swing.JLabel();
        lbAssunto_7 = new javax.swing.JLabel();
        lbAssunto_8 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Leitura e Aprendizagem");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Índice");

        lbAssunto_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_1.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_1.setText("Leitura e Aprendizagem > Matéria > Cadastrar");
        lbAssunto_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_1MousePressed(evt);
            }
        });

        lbAssunto_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_2.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_2.setText("Leitura e Aprendizagem > Matéria > Consultar");
        lbAssunto_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_2MousePressed(evt);
            }
        });

        lbAssunto_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_3.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_3.setText("Leitura e Aprendizagem > Categoria > Cadastrar");
        lbAssunto_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_3MousePressed(evt);
            }
        });

        lbAssunto_4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_4.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_4.setText("Leitura e Aprendizagem > Categoria > Consultar");
        lbAssunto_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_4MousePressed(evt);
            }
        });

        lbAssunto_5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_5.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_5.setText("Leitura e Aprendizagem > Subcategoria > Cadastrar");
        lbAssunto_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_5MousePressed(evt);
            }
        });

        lbAssunto_6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_6.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_6.setText("Leitura e Aprendizagem > Subcategoria > Consultar");
        lbAssunto_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_6MousePressed(evt);
            }
        });

        lbAssunto_7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_7.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_7.setText("Leitura e Aprendizagem > Assunto > Cadastrar");
        lbAssunto_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_7MousePressed(evt);
            }
        });

        lbAssunto_8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_8.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_8.setText("Leitura e Aprendizagem > Assunto > Consultar");
        lbAssunto_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(lbAssunto_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAssunto_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAssunto_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAssunto_8)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Índice", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbAssunto_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_1MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Cadastrar Matéria", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Materia_Cadastrar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_1MousePressed

    private void lbAssunto_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_2MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Consultar Matéria", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Materia_Consultar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_2MousePressed

    private void lbAssunto_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_3MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Cadastrar Categoria", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Categoria_Cadastrar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_3MousePressed

    private void lbAssunto_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_4MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Consultar Categoria", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Categoria_Consultar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_4MousePressed

    private void lbAssunto_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_5MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Cadastrar Subcategoria", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Subcategoria_Cadastrar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_5MousePressed

    private void lbAssunto_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_6MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Consultar Subcategoria", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Subcategoria_Consultar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_6MousePressed

    private void lbAssunto_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_7MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Cadastrar Assunto", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Assunto_Cadastrar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_7MousePressed

    private void lbAssunto_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_8MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabsAoHome( "Consultar Assunto", "/imagens_internas/livroTp.gif", 
                    new Leitura_e_Aprendizagem_Assunto_Consultar( Home ) );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_8MousePressed

    Exportando Exportando;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAssunto_1;
    private javax.swing.JLabel lbAssunto_2;
    private javax.swing.JLabel lbAssunto_3;
    private javax.swing.JLabel lbAssunto_4;
    private javax.swing.JLabel lbAssunto_5;
    private javax.swing.JLabel lbAssunto_6;
    private javax.swing.JLabel lbAssunto_7;
    private javax.swing.JLabel lbAssunto_8;
    // End of variables declaration//GEN-END:variables
   
}
